name: UAT env

on: 
  push:
    branches: [ kt_uat ]


jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UAT_HOST }}
        username: ${{ secrets.UAT_USER }}
        key: ${{ secrets.UAT_PUB_KEY }}
        script: |
            cd public_html
            git pull origin kt_uat

        
        